### ISSUE TITLE
send-password api

### ISSUE THREAD

**Issue by ddfridley** [EnCiv/undebate-ssp#154] opened 2022-05-26 19:35 UTC
The send password socket-api call is missing. This should be added to the civil-server repo.  
This is the code, taken from the original synaccord repo: 
```JS
'use strict';

import sequencer          from 'promise-sequencer';
import User               from '../models/user';
import sendEmail          from '../server/util/send-email';
import secret             from '../../secret.json';

function sendPassword (email, return_to, cb) {
  const { host } = this.handshake.headers;

  function emailBody (key, token) {
    const tail=token+(return_to||'');
    return secret['forgot password email']
      .replace(/\{key\}/g, key)
      .replace(/\{url\}/g, `http://${host}/page/reset-password/${tail}`);
  }

  new Promise((pass, fail) => {
    User
      .findOne({ email })

      .then(user => new Promise((pass, fail) => {
        if ( ! user ) {
          fail(new Error('User not found'));
        }

        else {
          sequencer(
            ()          =>    user.reactivate(),
            user        =>    sendEmail({
              from      :   secret.email.user,
              to        :   email,
              subject   :   'Reset password',
              text      :   emailBody(user.activation_key, user.activation_token)
            })
          ).then(pass, fail);
        }

      }).then(pass, fail))

      .catch(fail);
  })
    .then(cb)
    .catch(error => cb({ error : error.message }));
}

export default sendPassword;
```
In the above `secret['forgot password email']` is:
`"Hey,\r\n\r\nYou are receiving this email because you requested a password reset.\r\n\r\nYour reset key is:\r\n\r\n\t{key}\r\n\r\nTo reset your password, copy the reset key above and go to {url}\r\n\n\nThank you,\nThe Synaccord Team",
`

I didn't really need to be a secret. I would just include this text in the new send-password.js. In the future, or as a stretch goal, we can use SendInBlue to send the email, and create an HTML template for it.

It sends a link, that the users clicks on, that will take them to a page that will allow them to change their password. The link has a code in it, that is looked up in the database to find the user.
Here is the code for that route:
```JS
  resetPassword(){
    this.app.get(['/page/reset-password/:token','/page/reset-password/:token/*'], (req, res, next) => {
      try{
        if(req.params.token){
          User.findOne({activation_token: req.params.token}).then(user=>{
              if(user && user._id){
                req.user=user.toJSON();
                req.cookies.synuser={id: req.user._id, email: req.user.email} // passing the activation key also
                req.activation_key=user.activation_key;
                this.setUserCookie(req,res,next);
              }else
                next();
            },
            (error)=>{console.info("resetPassord found error",error); next(error)}
          )
        }
      }
      catch(error){
        next(error);
      }
    },serverReactRender.bind(this))
  }
```

- [ ] The reset password token should only be valid for 10 minutes. 
- [ ] Build a test for this. Do as much as you can with jest. But you may also have to build a app/web-component and test it with the dev server.
- [ ] Stretch goal: Build a cypress test for this.

**Comment by ice1080** [comment] 2022-10-03 02:58
@ddfridley is the original synaccord repo you mentioned a public repo? I did some searching and couldn't find it. The send-email file is missing from the above example. 
I'll eventually work on switching the above to SendInBlue, just figured I'd ask if you have it handy.

**Comment by ice1080** [comment] 2022-10-03 03:18
Also, I noticed that join.jsx in civil-client is currently unused. From what I can tell, I have to update loginForm.jsx in that project to add the resetPassword flow, would you like me to delete the unused Join file?

**Comment by ice1080** [comment] 2022-10-04 05:36
@ddfridley you mentioned using send-in-blue on civil-server. I noticed that there is currently neither send-in-blue nor nodemailer are setup in civil-server; just confirming that we do for sure want to add send-in-blue to this?

**Comment by ice1080** [comment] 2022-10-11 03:48
For historical tracking, I am copying the candidate-invitation template for the reset password template.
I am removing the unsubscribe section of the email since that's obviously not applicable here.

**Comment by ice1080** [comment] 2022-10-11 05:02
Hey @ddfridley, you mentioned a cypress test for this one in the description. I added a cypress test that creates a user, logs in as the user, and then sends the reset password email. I'm not sure it's possible to actually intercept the email request from the backend to send-in-blue (cypress only lets you intercept frontend to backend calls as far as I know).
If there is some way to seed the db with a user before running, then we should be able to insert a fake activationToken etc, and then test that the reset password link works and we can login with the new password after.

Alternatively, I can add some scripts to the package.json that perform what I mentioned using mongodb cli commands. I'll pursue that for now unless I hear back from you on a simpler way to seed and reset the db.

**Comment by ddfridley** [comment] 2022-10-11 06:34
I have no way to preppopulate users for cypress. A script sounds fine.

⁣Get BlueMail for Android ​

**Comment by ddfridley** [comment] 2022-10-11 07:52
For testing emails sendinblue has this that might be useful: https://github.com/sendinblue/APIv3-nodejs-library/blob/master/docs/InboundParsingApi.md#getInboundEmailEvents

I've never used it.

⁣Get BlueMail for Android ​

**Comment by ice1080** [comment] 2022-10-13 01:55
Just about have this issue complete. I see it working when running civil-server on its own, and just saw it working inside undebate-ssp too. Remaining work:
- update undebate-ssp to correctly handle the response from the reset-password socket
- create custom reset password page for undebate-ssp to match undebate-ssp signup/login popup
- stretch goal - rewrite authForm.jsx in civil-client to use the useAuth custom use-method

**Comment by ddfridley** [comment] 2022-10-13 06:16
Sorry. My mind is on vacation and only working in the background. About testing for this. I just realized that I had removed cypress because it was causing trouble when pushing undebate-ssp to heroku. Probably also causing problems for others building the repo too.

Did you install cypress? 

I have two thoughts. One is to abandon cypress. We are doing a lot more with jest than I had previously thought possible.  The other is to create a separate repo that imports cypress and civil-server and run the tests there. 

I wish npm had a testDependencies  section that is only installed at the top level. 

Thoughts?

David. 

⁣Get BlueMail for Android ​

**Comment by ice1080** [comment] 2022-10-13 14:03
Cypress is currently in the optional dependencies of civil-server and there is already an existing test in there. I was able to write some pretty good cypress tests for this flow in that repo so I was planning on leaving it at that. 
When you mention testDependencies, isn't that pretty much what the devDependencies are for? They don't get distributed with the prod build.

**Comment by ddfridley** [comment] 2022-10-13 17:50
Ok. My memory is faulty. I'm glad you didn't have to do a lot extra for cypress.

When you npm install a package like civil-server it's devDependencies are installed and built before building the package itself. But test dependences like cypress, jest, and storybook are not needed to build civil-server when it is installed in undebate-ssp. 

See the bottom of:

https://github.com/npm/cli/issues/3902


⁣Get BlueMail for Android ​

**Comment by ice1080** [comment] 2022-10-13 18:56
Ah ya that makes sense. Fyi though, most contributors of projects don't look at closed issues, so your comment will most likely stay ignored. I'd recommend opening a new issue and explaining why it's different than the other issue, or why it's not solved by the closing of the other issue.

**Comment by ice1080** [comment] 2022-10-19 23:59
Just got back from vacation so trying to get this one finished up. 
Our jest tests don't currently test any frontend interactions and it would take quite a bit to get to that point. 
As mentioned before, cypress is currently already installed in civil-server so I was using that to test many of these interactions. Is that alright to leave in there?
If we added cypress to undebate-ssp in the dev dependencies, would that still get packaged inside heroku? I know you said it would for dependencies' dev dependencies, but wasn't sure for direct dev dependencies.
Let me know how you'd like to proceed with this.

**Comment by ice1080** [comment] 2022-10-20 00:40
Another thing I just noticed was this error message code in civil-server:
```
function route() {
  const apiLimiter = expressRateLimit({
    windowMs: 60 * 1000,
    max: 2,
    message: 'Too many attempts logging in, please try again after 24 hours.',
  })  
  this.app.post('/sign/in', apiLimiter, signIn, this.setUserCookie, sendUserId)
}
```
The error message says to try again after 24 hours, but it really only checks that you don't try 3 times in a row within 60 seconds. Should I update the message or was this intentional? I waited 60 seconds instead of 24 hours and was able to sign in again.

**Comment by ddfridley** [comment] 2022-10-20 00:57
What if we do something based on NODE_ENV being development or production. For production it should be 24 hours.  for development it should be 60 seconds.

**Comment by ice1080** [comment] 2022-10-20 04:44
@ddfridley Phew this one was a doozy. Here are all three pull requests for this issue:
- civil-client: https://github.com/EnCiv/civil-client/pull/8
- civil-server: https://github.com/EnCiv/civil-server/pull/33
- undebate-ssp: https://github.com/EnCiv/undebate-ssp/pull/228

On civil-server you can run `npm run test` to see the jest tests passing, and you can run the dev server and run `npm run cypress:headless` or `npm run cypress` to see the cypress tests passing. I also confirmed that the jest tests on undebate-ssp were still passing.

In order to truly test all of this hooked together prior to merging the PRs, you would have to use temp branches. Here are the dependencies I was using in undebate-ssp's package.json, which should all be up to date. If you go this route, manually change them in package.json, then remove your node_modules and reinstall. Sometimes you have to use `npm uninstall <dependency>` to remove it from the npm cache too, and then reinstall it and move it back into the peerDependencies section.
- "civil-client": "github:ice1080/civil-client#undebate-ssp-send-password#154",
- "civil-server": "github:ice1080/civil-server#isaac-temp"
- "undebate": "github:ice1080/undebate#isaac-temp"

Let me know if you have any questions or changes!

**Closed** 2022-10-24 21:47 UTC
Labels: Javascript
