### ISSUE TITLE
Sign up/ Login cart breakdown

### ISSUE THREAD

**Issue by Saimurugeshwari** [EnCiv/undebate-ssp#238] opened 2024-02-24 21:45 UTC
Step to Reproduce:

Browser Version: Version 122.0.2365.52 (Official build) (64-bit)

1: Open the Undebate website in Microsoft Edge
2: Zoom the page until 100 or more.
3: click Sing up /Login button
4: Sign up and login button are hiding under the header.

Screen Shot:
![Screenshot 2024-02-24 133822](https://github.com/EnCiv/undebate-ssp/assets/103344341/d1df633c-1a36-4a38-8cfd-d05834bfb500)

**Comment by ddfridley** [comment] 2024-02-26 05:00
@Saimurugeshwari Can you send a screen shot of your whole display when you have this problem? What is the height of you viewport when you do this?  I realize that I can duplicate this problem when my viewport (window) is shorter than my display.  Is that there the issue is?  thx

**Comment by Saimurugeshwari** [comment] 2024-02-29 17:38
@ddfridley My computer Screen size: 18.4 in
Brand: Lenovo
Aspect ratio: 16:9
Resolution: 1920 x 1080

**Comment by ddfridley** [comment] 2024-02-29 21:34
@Saimurugeshwari I have pushed a fix for this to https://undebate-qa.herokuapp.com/undebates please check it.

**Closed** 2024-03-07 04:19 UTC
Labels: bug, help wanted
